name: Tests

on: [push, pull_request]

env:
  SCARB_VERSION: 0.5.0-alpha.3

jobs:
  scarb-test:
    name: scarb_test ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: linux x86-64
            os: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Scarb for Linux
        if: matrix.os == 'ubuntu-latest'
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://docs.swmansion.com/scarb/install.sh | bash -s -- -v "$SCARB_VERSION"
      - run: cd alexandria/math && scarb build && scarb test
